# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "Build Release APK"

  lane :release_apk do

    gradle(
      task: "assembleRelease"
    )

  end

  desc "Build Release AAB"

  lane :release_aab do

    gradle(
      task: "bundleRelease"
    )

  end

  desc "Upload to Internal Testing"

  lane :internal do

    gradle(
      task: "bundleRelease"
    )

    upload_to_play_store(
      track: 'internal',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )

  end

end
