name: Android CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission
        run: chmod +x gradlew

      - name: Decode Keystore
        run: |
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_BASE64 }}" > keystore.base64
          base64 --decode keystore.base64 > app/keystore/release-key.jks

      - name: Create Keystore Properties
        run: |
          echo "storePassword=${{ secrets.STORE_PASSWORD }}" >> keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> keystore.properties
          echo "storeFile=app/release-key.jks" >> keystore.properties

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Android Lint
        run: ./gradlew lint

      - name: Increment Version Code
        run: ./gradlew incrementVersionCode

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

      - name: Upload APK to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: Android_Tester
          file: app/build/outputs/apk/release/app-release.apk